[package]
name = "rr4r"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr", branch = "more-wrapper-tidying" }
regex = "1"
lru = "*"
